{% set name = "pephubclient" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pephubclient-{{ version }}.tar.gz
  sha256: 06cddb4b961c325eae07934e88fd342a56b5bd00cd2b0bfda7c86d3cf00ff599

build:
  entry_points:
    - phc = pephubclient.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - typer >=0.7.0
    - peppy >=0.40.5
    - requests >=2.28.2
    - pydantic >=2.5.0
    - pandas >=2.0.0
    - ubiquerg >=0.6.3
    - coloredlogs >=15.0.1

test:
  imports:
    - pephubclient
  commands:
    - phc --help

about:
  home: https://github.com/databio/pephubclient/
  summary: PEPhub command line interface.
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - khoroshevskyi
