{% set name = "pephubclient" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pephubclient-{{ version }}.tar.gz
  sha256: 41a8b7af90477c027f0f9205383178381a2bd042d2da18d9e047be81d9597b7a

build:
  entry_points:
    - phc = pephubclient.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - typer >=0.7.0
    - peppy >=0.40.5
    - requests >=2.28.2
    - pydantic >=2.5.0
    - pandas >=2.0.0
    - ubiquerg >=0.6.3
    - coloredlogs >=15.0.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - pephubclient
  commands:
    - phc --help

about:
  home: https://github.com/databio/pephubclient/
  summary: PEPhub command line interface.
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - khoroshevskyi
